export default {
    GET_ALBUM_START: "GET_ALBUM_START",
    GET_ALBUM_SUCCESS: "GET_ALBUM_SUCCESS",
    GET_ALBUM_FAIL: "GET_ALBUM_FAIL",

    GET_ALBUM_PLAYLIST_START: "GET_ALBUM_PLAYLIST_START",
    GET_ALBUM_PLAYLIST_SUCCESS: "GET_ALBUM_PLAYLIST_SUCCESS",
    GET_ALBUM_PLAYLIST_FAIL: "GET_ALBUM_PLAYLIST_FAIL",

    PLAY_ALBUM: "PLAY_ALBUM",
};
