export default {
    OPEN_AUDIO_MENU: "OPEN_AUDIO_MENU",
    CLOSE_AUDIO_MENU: "CLOSE_AUDIO_MENU",

    PLAY_AUDIO: "PLAY_AUDIO",
    LOAD_AUDIO_SUCCESS: "LOAD_AUDIO_SUCCESS",
    LOAD_AUDIO_FAIL: "LOAD_AUDIO_FAIL",

    GET_AUDIO_START: "GET_AUDIO_START",
    GET_AUDIO_SUCCESS: "GET_AUDIO_SUCCESS",
    GET_AUDIO_FAIL: "GET_AUDIO_FAIL",

    PLAY_NEXT: "PLAY_NEXT",
    PLAY_PREV: "PLAY_PREV",

    // Player Action types
    ON_PROGRESS: "ON_PROGRESS",
    ON_DURATION: "ON_DURATION",
    ON_ENDED: "ON_ENDED",
    ON_SEEK_MOUSEDOWN: "ON_SEEK_MOUSEDOWN",
    ON_SEEK_MOUSEUP: "ON_SEEK_MOUSEUP",
    ON_SEEK_CHANGE: "ON_SEEK_CHANGE",
    PLAY_PAUSE: "PLAY_PAUSE",
    TOGGLE_LOOP: "TOGGLE_LOOP",
    TOGGLE_MUTE: "TOGGLE_MUTE",
    TOGGLE_SHUFFLE: "TOGGLE_SHUFFLE",
    CHANGE_VOLUME: "CHANGE_VOLUME",
};
